spring:
  application:
    name: task-master
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/waim
    username: waimadm
    password: crependev1!
  config:
    import: classpath:waim.yml
  data:
    redis:
      connect-timeout: 2000ms
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8082
