server:
  port: 18080

spring:
  config:
    import: classpath:waim-local.yml

  datasource:
    url: jdbc:mariadb://localhost:3306/waim?serverTimezone=UTC&forceConnectionTimeZone=true&connectionTimeZone=UTC
    username: waimadm
    password: crependev1!

  data:
    redis:
      host: localhost
      port: 6379
      password: qwer1234
      connect-timeout: 5000ms
      timeout: 3000ms
      client-type: lettuce
      lettuce:
        shutdown-timeout: 500ms
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  rabbitmq:
    host: localhost
    port: 15677
    username: admin
    password: admin_password

  jpa:
    hibernate:
      ddl-auto: update
