services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: waim-rabbitmq
    ports:
      - 15677:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin_password
